books_list/urls.py
from django.contrib import admin
from django.urls import path

from books.views import AllBooksView, AddEditBookView, ImportBookView, BookAPIView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', AllBooksView.as_view(), name='all_books'),
    path('add_book/', AddEditBookView.as_view(), name='add_book'),
    path('import_books/', ImportBookView.as_view(), name='import_books'),
    path('book_api/', BookAPIView.as_view(), name='books_api'),
]

books/models.py
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator
from django.conf.global_settings import LANGUAGES


# Create your models here.


class Book(models.Model):
    title = models.CharField(max_length=128, verbose_name='Tytuł')
    author = models.CharField(max_length=128, verbose_name='Autor', null=True, blank=True)
    published_date = models.IntegerField(validators=[MinValueValidator(0), MaxValueValidator(9999)],
                                         verbose_name='Data publikacji')
    isbn = models.CharField(max_length=18, null=True, blank=True, verbose_name='ISBN')
    page_count = models.IntegerField(verbose_name='Ilość stron', blank=True, null=True)
    image_link = models.URLField(blank=True, null=True, verbose_name='Link do zdjęcia okładki')
    language = models.CharField(max_length=7, choices=LANGUAGES, blank=True, null=True, verbose_name='Język')

    def __str__(self):
        return self.title

books/forms.py
from django import forms
from django.conf.global_settings import LANGUAGES
import datetime
import pyisbn
from django.core.exceptions import ValidationError
from books.models import Book


LANGUAGES_EMPTY = [('', 'wybierz język')] + LANGUAGES


def validate_year(year):
    this_year = datetime.datetime.now().year
    if year < 0:
        raise ValidationError('Rok publikacji nie może być mniejszy od 0!')
    elif year > this_year:
        raise ValidationError('Rok publikacji nie może być większy niż {}!'.format(this_year))


def validate_isbn(isbn):
    if not pyisbn.validate(isbn):
        raise ValidationError('Nieprawidłowy numer ISBN!')


class SearchBookForm(forms.Form):
    title = forms.CharField(max_length=128, label='Tytuł', required=False)
    author = forms.CharField(max_length=128, label='Autor', required=False)
    language = forms.ChoiceField(choices=LANGUAGES_EMPTY, label='Język', required=False)
    published_date_from = forms.IntegerField(label='Data publikacji od', required=False, validators=[validate_year])
    published_date_to = forms.IntegerField(label='Data publikacji do', required=False, validators=[validate_year])


class AddEditBookForm(forms.ModelForm):
    published_date = forms.IntegerField(label='Data publikacji', validators=[validate_year])
    isbn = forms.CharField(label='ISBN', validators=[validate_isbn], required=False)

    class Meta:
        model = Book
        fields = '__all__'


class ImportBookForm(forms.Form):
    title = forms.CharField(label='Tytuł', required=False)
    author = forms.CharField(label='Autor', required=False)
    isbn = forms.CharField(label='ISBN', required=False)

books/views.py
import requests
from django.shortcuts import render, redirect
from rest_framework import generics, filters
from rest_framework.permissions import IsAuthenticatedOrReadOnly
from django.contrib import messages
from books.forms import SearchBookForm, AddEditBookForm, ImportBookForm
from books.serializers import BookSerializer
from books.models import Book
from django.views import View


# Create your views here.


class AllBooksView(View):
    def get(self, request):
        books = Book.objects.all().order_by('-id')
        form = SearchBookForm()
        return render(request, 'all_books.html', {
            'books': books,
            'form': form
        })

    def post(self, request):
        if request.POST['action'] == 'search':
            form = SearchBookForm(request.POST)
            books = Book.objects.all().order_by('-id')
            if form.is_valid():
                title = form.cleaned_data['title']
                author = form.cleaned_data['author']
                language = form.cleaned_data['language']
                published_date_from = form.cleaned_data['published_date_from']
                published_date_to = form.cleaned_data['published_date_to']

                if title:
                    books = books.filter(title__icontains=title)
                if author:
                    books = books.filter(author__icontains=author)
                if language:
                    books = books.filter(language__icontains=language)
                if published_date_from:
                    books = books.filter(published_date__gte=published_date_from)
                if published_date_to:
                    books = books.filter(published_date__lte=published_date_to)
                form = SearchBookForm()
            return render(request, 'all_books.html', {
                'books': books,
                'form': form
            })

        if request.POST['action'] == 'del':
            book_id = request.POST['book_id']
            book = Book.objects.get(pk=book_id)
            book.delete()
            return redirect('all_books')

        if request.POST['action'] == 'edit':
            book_id = request.POST['book_id']
            book = Book.objects.get(pk=book_id)
            form = AddEditBookForm(instance=book)
            return render(request, 'add_edit_book.html', {
                'form': form,
                'book': book
            })


class AddEditBookView(View):
    def get(self, request):
        form = AddEditBookForm()
        return render(request, 'add_edit_book.html', {'form': form})

    def post(self, request):
        if request.POST['action'] == 'add':
            form = AddEditBookForm(request.POST)
            if form.is_valid():
                book = form.save(commit=False)
                isbn = form.cleaned_data['isbn']
                if '-' in isbn:
                    split_isbn = isbn.split('-')
                    clear_isbn = ''.join(split_isbn)
                    book.isbn = clear_isbn
                book.save()
                return redirect('all_books')
            return render(request, 'add_edit_book.html', {'form': form})

        if request.POST['action'] == 'edit':
            form = AddEditBookForm(request.POST)
            if form.is_valid():
                book_id = request.POST['book_id']
                book = Book.objects.get(pk=book_id)
                form = AddEditBookForm(request.POST, instance=book)
                book = form.save(commit=False)
                isbn = form.cleaned_data['isbn']
                print(isbn)
                if '-' in isbn:
                    split_isbn = isbn.split('-')
                    clear_isbn = ''.join(split_isbn)
                    book.isbn = clear_isbn
                    print(clear_isbn)
                book.save()
                return redirect('all_books')
            return render(request, 'add_edit_book.html', {'form': form})


class ImportBookView(View):
    def get(self, request):
        form = ImportBookForm()
        return render(request, 'import_books.html', {'form': form})

    def post(self, request):
        form = ImportBookForm(request.POST)
        if form.is_valid():
            title = form.cleaned_data['title']
            author = form.cleaned_data['author']
            isbn = form.cleaned_data['isbn']
            keywords = [title, author, isbn]

            title_qs = '+intitle:' + title
            author_qs = '+inauthor:' + author
            isbn_qs = '+isbn:' + isbn
            req_url = 'https://www.googleapis.com/books/v1/volumes?q=Hobbit'
            for keyword in keywords:
                if keyword:
                    if keyword == title:
                        req_url += title_qs
                    if keyword == author:
                        req_url += author_qs
                    if keyword == isbn:
                        req_url += isbn_qs

            books_request = requests.get(url=req_url)
            books_json = books_request.json()
            try:
                books = books_json['items']
            except Exception:
                messages.warning(request, 'Brak książek do zaimportowania!')
                form = ImportBookForm()
                return render(request, 'import_books.html', {'form': form})

            for book in books:

                if 'authors' in book['volumeInfo']:
                    authors = book['volumeInfo']['authors']
                    author = ''
                    for a in authors:
                        author += a
                else:
                    author = None

                if 'industryIdentifiers' in book['volumeInfo']:
                    isbn = book['volumeInfo']['industryIdentifiers'][0]['identifier']
                else:
                    isbn = None

                published_date = book['volumeInfo']['publishedDate']
                if '-' in published_date:
                    pd = published_date.split('-')
                    published_date = ''
                    for i in pd[0]:
                        if i.isdigit():
                            published_date += i


                if 'imageLinks' in book['volumeInfo']:
                    image_link = book['volumeInfo']['imageLinks']['thumbnail']
                else:
                    image_link = None

                if 'pageCount' in book['volumeInfo']:
                    pagecount = book['volumeInfo']['pageCount']

                else:
                    pagecount = 0

                if 'language' in book['volumeInfo']:
                    language = book['volumeInfo']['language']
                else:
                    language = None

                Book.objects.get_or_create(
                    title=book['volumeInfo']['title'],
                    author=author,
                    published_date=published_date,
                    isbn=isbn,
                    page_count=pagecount,
                    image_link=image_link,
                    language=language
                )
            return redirect('all_books')
        return render(request, 'import_books.html', {'form': form})


class BookAPIView(generics.ListCreateAPIView):
    search_fields = ['title', 'author', 'language', 'published_date']
    filter_backends = (filters.SearchFilter,)
    queryset = Book.objects.all()
    serializer_class = BookSerializer
    permission_classes = [IsAuthenticatedOrReadOnly]

books/templates/add_edit_book.html
{% extends 'base.html' %}

{% block content %}
{% if book %}
<h1>Edytuj książkę</h1>
<div>
    <form action="{% url 'add_book' %}" method="post">{% csrf_token %}
        {{ form.as_p }}
        <br>
        <input id="{{ book.id }}" name="book_id" type="hidden" value="{{ book.id }}">
        <button type="submit" name="action" value="edit">Zmień</button>
    </form>
    <br>
</div>
{% else %}
<h1>Dodaj książkę</h1>
<div>
    <form action="{% url 'add_book' %}" method="post">{% csrf_token %}
        {{ form.as_p }}
        <br>
        <button type="submit" name="action" value="add">Dodaj</button>
    </form>
    <br>
</div>
<a href="{% url 'all_books' %}"><button>Powrót do listy książek</button></a>
{% endif %}
{% endblock %}

books/templates/all_books.html
{% extends 'base.html' %}

{% block content %}
<h1>Wyszukiwarka książek</h1>
<div>
    <form action="{% url 'all_books' %}" method="post">{% csrf_token %}
        {{ form.as_p }}
        <br>
        <button type="submit" name="action" value="search">Szukaj</button>
    </form>
    <br>
    <a href="{% url 'add_book' %}"><button>Dodaj książkę</button></a>
    <br>
    <br>
    <a style="margin-right: 890px" href="{% url 'import_books' %}"><button>Importuj książki</button></a>
    <a href="{% url 'books_api' %}"><button>REST API</button></a>
    <br>
</div>
<div>
    <table  class="table table-dark">
        <h2>Lista książek</h2>
        <tr>
            <th>Tytuł</th>
            <th>Autor</th>
            <th>Data publikacji</th>
            <th>ISBN</th>
            <th>Liczba stron</th>
            <th>Zdjęcie okładki</th>
            <th>Język</th>
        </tr>

        {% for book in books %}
        <form action="{% url 'all_books' %}" method="post">{% csrf_token %}
            <tr>
                <td>{{ book.title }}</td>
                <td>{{ book.author }}</td>
                <td>{{ book.published_date }}</td>
                <td>{{ book.isbn | default_if_none:"-" }}</td>
                <td>{{ book.page_count }}</td>
                {% if book.image_link == None %}
                <td>-</td>
                {% else %}
                <td><a href='{{ book.image_link | default_if_none:"-" }}'>{{ book.image_link | default_if_none:"-" }}</a></td>
                {% endif %}
                <td>{{ book.get_language_display }}</td>
                <td>
                    <input id="{{ book.id }}" name="book_id" type="hidden" value="{{ book.id }}">
                    <button type="submit" name="action" value="edit">Edytuj</button>
                </td>
                <td>
                    <input name="book_id" type="hidden" value="{{ book.id }}">
                    <button type="submit" name="action" value="del">Usuń</button>
                </td>

            </tr>
        </form>

        {% endfor %}



    </table>
</div>
{% endblock %}

books/templates/base.html
<!doctype html>

<html>
    <head>
        <meta charset="utf-8">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    </head>
    <body>
    <div class="container">
    {% load static %}
    {%   if messages %}
                <div class="container">
                {% for message in messages %}
                    <button{% if message.tags %} class="btn btn-{{ message.tags }} btn-block"{% endif %}>{{ message }}</button>
                {% endfor %}
                </div>
    {% endif %}
    {%  block content %}
    {%  endblock %}
    </div>

    </body>
</html>

books/templates/import_books.html
{% extends 'base.html' %}

{% block content %}
<h1>Importowanie książek z API:
https://www.googleapis.com/books/v1/volumes?q=Hobbit</h1>
<div>
    <form action="{% url 'import_books' %}" method="post">{% csrf_token %}
        {{ form.as_p }}
        <br>
        <button type="submit" name="action" value="search">Importuj do bazy danych</button>
    </form>
    <br>
    <a href="{% url 'all_books' %}"><button>Powrót do listy książek</button></a>

</div>
{% endblock %}